ALTER SESSION SET STATISTICS_LEVEL = ALL;

select /*+INDEX(CUSTOM_주문14 IDX_주문14) */ * from CUSTOM_주문14 WHERE 고객번호 = 'C0191';


/*
 INDEX 생성
 */
CREATE INDEX IDX_주문14 ON CUSTOM_주문14('고객번호');

COMMIT;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR(NULL, NULL, 'ALLSTATS LAST'));